### ISSUE TITLE
Star Rating

### ISSUE THREAD

**Issue by batshell** [matt-daneshvar/laravel-survey#23]
Can you please add a feature to have star ratings out of 5 stars along with results i.e. the average star rating that all the users gave? It would be very helpful.

**Comment by matt-daneshvar** [comment]
Hi Shailendra, thanks for checking out the package. That sounds like a useful feature. I may not have the capacity to work on it soon, but happy to review a PR for it.

**Comment by LufoX11** [comment]
@batshell I've implemented this package: https://plugins.krajee.com/star-rating-demo-advanced-usage
I'm not making a PR since I don't know if it's ok to bring on an external package, and if it's possible, I don't know the right way to do it. On the other hand, it's really simple to do it, just export the built-in view components, add a new view with some name like "rating.blade.php" and do the magic inside.
