### ISSUE TITLE
Need help about multi steps

### ISSUE THREAD

**Issue by dzymail** [matt-daneshvar/laravel-survey#26]
Hi, could anyone help me about multi steps form?

my app have 108 questions, all of which are mandatory. The first 8 questions are the basic information of the client filling in, including text type and radio type. The next 100 questions are for analysis, all of which are radio types. now i got single page form working, but not for multi steps.

I plan to split into 8+20+20+20+20+20 steps, how to adjust blade file? i defined function for step number increase, and the variables for blade file, something like this:

>             
$step1 = $survey->questions->slice(0, 8, true);
            $step2 = $survey->questions->slice(8, 20, true);
            $step3 = $survey->questions->slice(28, 20, true);
            $step4 = $survey->questions->slice(48, 20, true);
            $step5 = $survey->questions->slice(68, 20, true);
            $step6 = $survey->questions->slice(88, 20, true);

> 
@if($currentStep == 1)
            @foreach($step1 as $key => $question)
                @include('survey::questions.single')
            @endforeach
@endif

but not working, maybe related to pass variables between steps, please give some details about how to do multi steps?

**Comment by matt-daneshvar** [comment]
Hi @dzymail, thanks for trying out this package. We don't have a multi-step wizard-like structure built in, but here are a couple of ideas you may find useful: 

### Grouping questions into multiple sections
Consider using [sections](https://github.com/matt-daneshvar/laravel-survey#creating-multiple-sections):
```php
$survey = Survey::create(['name' => 'Cat Population Survey']);

$one = $survey->sections()->create(['name' => 'Part One']);

$one->questions()->create([
    'content' => 'How many cats do you have?',
    'type' => 'number',
    'rules' => ['numeric', 'min:0']
]);

$two = $survey->sections()->create(['name' => 'Part Two']);

$two->questions()->create([
    'content' => 'What\'s the name of your first cat?',
]);

$two->questions()->create([
    'content' => 'Would you want a new cat?',
    'type' => 'radio',
    'options' => ['Yes', 'Oui']
]);
//...
```
This way you won't have to deal with slicing questions manually when accessing them in your blade file:
```blade
@foreach($survey->sections as $section)
  <h2>{{ $section->name }}</h2>

  @foreach($section->questions as $question)   
      @include('survey::questions.single')
  @endforeach
@endforeach
```

### Displaying one section at a time
One way to approach this is to modify the views that come with this package and add a sprinkle of JavaScript to acheive the user experience you intend. To do this, I would: 

#### 1. Publish the boilerplate views
```
php artisan vendor:publish --provider="MattDaneshvar\Survey\SurveyServiceProvider" --tag="views"
```
This will create a new `vendor/survey` directory under your views directory, where you can fully modify the blade files that come with this package. 

#### 2. Write your own JavaScript or make use of an open-source package 
I did a quick search and came across [techlab/jquery-smartwizard](https://github.com/techlab/jquery-smartwizard). You may find other packages that suit your requirements better.

### Challenges to consider when building a wizard with JS
Here are a couple of challenges I can think of when using JavaScript to achieve this style of navigation: 

- What happens if a user accidentally reload the form? Will they need to fill up the entire 108 questions again? You may find packages like [guillaumepotier/garlic.js](https://github.com/guillaumepotier/garlic.js) useful to maintain form values locally until the form is submitted. 

- What if the answer to a question in the 3rd section is invalid? Will the wizard be able to automatically display the 3rd section when Laravel's validation redirects user back to the form? 

---
Leaving this issue open so that it's visible to others who may be able to provide more help.

**Comment by dzymail** [comment]
It is related javascript. i tried manually bind fields value when using Livewire, but that is not a general solution. thanks for the reply.

**Comment by Mathias-Wa-Mucani** [comment]
Thanks @matt-daneshvar for this great package. I'm wondering if there's a way around matrix questions, more like table formats. And also how can one send the form data using ajax to the backend?
Thank you advance!

**Comment by matt-daneshvar** [comment]
Hey @Mathias-Wa-Mucani, thanks for the interest. I'm sending you these notes with some help from Claude: 

### Matrix / table questions

The package doesn't have a dedicated matrix question type, but you might be able to achieve the same thing by modeling each row as its own `radio` question and grouping them inside a `Section`. For example, a "Rate our service" matrix with rows for Price, Quality, and Speed would look like:

```php
$section = $survey->sections()->create(['name' => 'Rate our service']);

$section->questions()->create([
    'content' => 'Price',
    'type' => 'radio',
    'options' => ['Poor', 'Fair', 'Good', 'Excellent'],
]);

$section->questions()->create([
    'content' => 'Quality',
    'type' => 'radio',
    'options' => ['Poor', 'Fair', 'Good', 'Excellent'],
]);

$section->questions()->create([
    'content' => 'Speed',
    'type' => 'radio',
    'options' => ['Poor', 'Fair', 'Good', 'Excellent'],
]);
```

This way validation, storage, and results all work out of the box. If you want the visual table layout, you can publish the views and customize the section template to render its questions as a table grid.

### AJAX submission

The package handles storage through the `Entry` model, not a built-in controller, so you're free to submit however you like. A minimal example:

```js
// Collect answers in { q1: "Good", q2: "5", ... } format
const answers = Object.fromEntries(new FormData(formEl));

fetch('/your-survey-endpoint', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
    },
    body: JSON.stringify({ answers }),
});
```

```php
// In your controller 
public function store(Request $request, Survey $survey)
{
    $request->validate($survey->rules);

    (new Entry)
        ->for($survey)
        ->by(auth()->user())
        ->fromArray($request->input('answers'))
        ->push();

    return response()->json(['message' => 'Thanks!']);
}
```

**Comment by Mathias-Wa-Mucani** [comment]
Hello Matt-Daneshvar, I appreciate this prompt response. Will try it out in
my use case and see how it goes.

Kind regards.
__________________________________________________
*Mathias Mulumba Mucani* | *Software Developer* | *ERP Consultant*

*+256702881399*
